[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/config"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"