[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "src/service-worker.js"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-site"

[[headers]]
  for = "/src/index.js"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-site"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-site"


[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cross-Origin-Resource-Policy = "same-site"